// ข้อความภาษาไทยทั้งหมดอยู่ที่นี่ เปลี่ยนคำศัพท์ (เช่น นักเรียน → ผู้สมัคร) ที่เดียว
window.DSSI_STRINGS = {
  course: 'หลักสูตร Data Science and Software Innovation · มหาวิทยาลัยอุบลราชธานี',
  logoAlt: 'DSSI',
  examinee: 'นักเรียน',
  interviewer: 'อาจารย์',

  err: {
    network: 'เชื่อมต่อไม่ได้ กำลังลองใหม่...',
    generic: 'ระบบมีปัญหา ลองใหม่อีกครั้ง',
    needId: 'กรอกรหัสนักเรียนก่อน',
    needLogin: 'กรอกชื่อ รหัสผ่าน และรหัสรอบให้ครบ',
    needMeet: 'วางลิงก์ Google Meet ที่ขึ้นต้นด้วย https://meet.google.com/',
    sessionExpired: 'เซสชันหมดอายุ เข้าสู่ระบบใหม่อีกครั้ง',
  },

  student: {
    navTeacher: 'สำหรับอาจารย์',
    // หน้ากรอกรหัส
    idTitleTop: 'ตรวจสอบ',
    idTitleGrad: 'คิวสอบ',
    idLead: 'กรอกรหัสนักเรียนเพื่อดูตำแหน่งคิวสัมภาษณ์ของคุณ',
    idLabel: 'รหัสนักเรียน',
    idSubmit: 'ดูคิวของฉัน',
    // รอคิว
    badgeWait: function (round, n) { return 'รอบ ' + round + ' มีอาจารย์ว่าง ' + n + ' ท่าน'; },
    youAre: 'คุณอยู่',
    queueNo: function (n) { return 'คิวที่ ' + n; },
    waitLead: 'รออาจารย์ว่าง หน้านี้อัปเดตเอง ไม่ต้องรีเฟรช',
    you: 'คุณ',
    aheadLabel: function (n) { return 'ข้างหน้า ' + n + ' คน'; },
    behindLabel: function (n) { return 'ข้างหลัง ' + n + ' คน'; },
    idCard: 'รหัสนักเรียน',
    roundTag: function (r) { return 'รอบ ' + r; },
    changeId: 'เปลี่ยนรหัสนักเรียน',
    // ถึงคิว
    badgeBusy: 'อาจารย์รออยู่ในห้องแล้ว',
    busyTop: 'ถึงคิว',
    busyGrad: 'คุณแล้ว',
    busyLead: 'กดปุ่มเพื่อเข้าห้อง Meet ของอาจารย์ผู้สัมภาษณ์',
    teacherLabel: 'อาจารย์ผู้สัมภาษณ์',
    meetRoom: 'ห้อง Google Meet',
    joinMeet: 'เข้าห้อง Meet',
    meetInvalid: 'ลิงก์ห้อง Meet ไม่ถูกต้อง ติดต่อกรรมการ',
    // เสร็จ
    badgeDone: 'สัมภาษณ์เสร็จแล้ว',
    doneTop: 'เสร็จสิ้น',
    doneGrad: 'ขอบคุณ',
    doneLead: 'คุณสัมภาษณ์เสร็จแล้ว ปิดหน้านี้ได้เลย',
  },

  teacher: {
    navStudent: 'หน้านักเรียน',
    // login
    loginTop: 'สำหรับ',
    loginGrad: 'อาจารย์',
    loginLead: 'เลือกชื่อ กรอกรหัสผ่าน และรหัสรอบที่คุณสัมภาษณ์',
    name: 'ชื่ออาจารย์',
    namePlaceholder: 'เลือกชื่อ',
    password: 'รหัสผ่าน',
    round: 'รหัสรอบ',
    login: 'เข้าสู่ระบบ',
    loadingTeachers: 'กำลังโหลดรายชื่อ...',
    // หลังล็อกอิน
    badge: { free: 'ว่าง พร้อมรับคิว', busy: 'สัมภาษณ์อยู่', rest: 'พัก ไม่รับคิว' },
    roundTag: function (r) { return 'รอบ ' + r; },
    busyTop: 'กำลังสัมภาษณ์',
    freeTop: 'พร้อมรับ',
    freeGrad: 'คิวถัดไป',
    restTop: 'พักอยู่',
    restGrad: 'ยังไม่รับคิว',
    doneTop: 'สัมภาษณ์',
    doneGrad: 'ครบแล้ว',
    freeWaiting: function (n) { return 'มีคนรอ ' + n + ' คน ระบบจะจับคู่ให้ทันที'; },
    freeEmpty: 'ยังไม่มีคนรอ หน้านี้อัปเดตเอง',
    restLead: 'วางลิงก์ Meet แล้วกด "ว่าง รับคิวต่อไป" เมื่อพร้อม',
    allDone: 'ไม่มีนักเรียนเหลือในรอบนี้แล้ว',
    meetLabel: 'ลิงก์ Google Meet',
    meetPlaceholder: 'https://meet.google.com/abc-defg-hij',
    statWaiting: 'คนรอ',
    statDone: 'สัมภาษณ์เสร็จแล้ว',
    openMeet: 'เปิดห้อง Meet',
    finish: 'สัมภาษณ์เสร็จ รับคนถัดไป',
    rest: 'พัก',
    free: 'ว่าง รับคิวต่อไป',
    logout: 'ออกจากระบบ',
    studentId: function (id) { return 'รหัส ' + id; },
  },
};
